# Generated by Django 5.2.6 on 2026-04-20 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarFeed",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Patrons Calendar", max_length=100)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("confirmation_name", models.CharField(blank=True, max_length=100)),
                ("maiden_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("last_name", "first_name", "middle_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("first_name", "middle_name", "confirmation_name", "maiden_name", "last_name"),
                        name="unique_patron_family_member_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday"),
                            ("baptism", "Baptism Day"),
                            ("wedding", "Wedding Day"),
                            ("confirmation", "Confirmation Day"),
                            ("first_confession", "First Confession Day"),
                            ("first_communion", "First Communion Day"),
                            ("diaconal_ordination", "Diaconal Ordination Day"),
                            ("priestly_ordination", "Priestly Ordination Day"),
                            ("death", "Death Day"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "family_member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="patrons.familymember"),
                ),
            ],
            options={
                "ordering": ("family_member__last_name", "family_member__first_name", "date"),
            },
        ),
        migrations.CreateModel(
            name="PatronalFeast",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("normalized_name", models.CharField(max_length=255)),
                ("feast_name", models.CharField(max_length=255)),
                ("general_calendar_name", models.CharField(blank=True, max_length=255)),
                ("traditional_calendar_name", models.CharField(blank=True, max_length=255)),
                ("episcopal_calendar_name", models.CharField(blank=True, max_length=255)),
                ("general_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("general_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("traditional_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("traditional_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("episcopal_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("episcopal_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "family_member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="patrons.familymember"),
                ),
            ],
            options={
                "ordering": ("family_member__last_name", "family_member__first_name", "normalized_name", "feast_name"),
            },
        ),
        migrations.CreateModel(
            name="TextRecipient",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("telephone_number", models.CharField(max_length=32)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "family_member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="patrons.familymember"),
                ),
            ],
            options={
                "ordering": ("family_member__last_name", "family_member__first_name", "telephone_number"),
            },
        ),
        migrations.CreateModel(
            name="TextSchedule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("time", models.TimeField(help_text="Eastern time")),
                (
                    "relative_days",
                    models.IntegerField(
                        default=0,
                        help_text="-1 is one day before the event, 0 is the day of the event, and 1 is one day after.",
                    ),
                ),
            ],
            options={
                "ordering": ("relative_days", "time"),
                "constraints": [
                    models.UniqueConstraint(fields=("time", "relative_days"), name="unique_patron_text_schedule")
                ],
            },
        ),
        migrations.CreateModel(
            name="TextMessageSend",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurrence_date", models.DateField()),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("success", models.BooleanField(default=False)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="patrons.event"
                    ),
                ),
                (
                    "patronal_feast",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="patrons.patronalfeast"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="patrons.textrecipient"),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="patrons.textschedule"
                    ),
                ),
            ],
            options={
                "ordering": ("-attempted_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("family_member", "event_type", "date"), name="unique_patron_event_for_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="patronalfeast",
            constraint=models.UniqueConstraint(
                fields=("family_member", "normalized_name", "feast_name"), name="unique_patronal_feast_for_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="textrecipient",
            constraint=models.UniqueConstraint(
                fields=("family_member", "telephone_number"), name="unique_patron_text_recipient_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="textmessagesend",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event__isnull", False), ("patronal_feast__isnull", True)),
                    models.Q(("event__isnull", True), ("patronal_feast__isnull", False)),
                    _connector="OR",
                ),
                name="patron_send_has_event_or_feast",
            ),
        ),
        migrations.AddConstraint(
            model_name="textmessagesend",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("recipient", "schedule", "event", "occurrence_date"),
                name="unique_patron_event_send",
            ),
        ),
        migrations.AddConstraint(
            model_name="textmessagesend",
            constraint=models.UniqueConstraint(
                condition=models.Q(("patronal_feast__isnull", False)),
                fields=("recipient", "schedule", "patronal_feast", "occurrence_date"),
                name="unique_patron_feast_send",
            ),
        ),
    ]
