# Generated by Django 2.2.6 on 2019-10-23 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("office", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ThirtyDayPsalterDay",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("day", models.IntegerField()),
                ("mp_psalms", models.CharField(max_length=255)),
                ("ep_psalms", models.CharField(max_length=255)),
            ],
            options={"abstract": False},
        )
    ]
