# Generated by Django 3.0.6 on 2020-05-07 02:21

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0002_thirtydaypsalterday"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutItem",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("question", ckeditor.fields.RichTextField()),
                ("answer", ckeditor.fields.RichTextField()),
                ("app_mode", models.BooleanField(default=True)),
                ("web_mode", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
