# Generated by Django 3.2.7 on 2021-10-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0005_auto_20200519_2249"),
    ]

    operations = [
        migrations.AddField(
            model_name="holydayofficeday",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
