# Generated by Django 4.0.2 on 2022-02-22 03:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0007_setting_settingoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectCategory",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "collect_type",
                    models.CharField(
                        choices=[
                            ("collect", "Collects of the Christian Year"),
                            ("occasional", "Occasional Prayers"),
                            ("office_prayers", "Collects from the Daily Office"),
                            ("burial_rite", "Collects from the Burial Rite"),
                            ("other", "Other Collects"),
                        ],
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("attribution", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "collect_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="office.collectcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
