# Generated by Django 4.0.2 on 2022-03-20 02:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0008_collectcategory_collect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
