# Generated by Django 4.0.4 on 2022-08-07 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0010_move_collects_to_foreign_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scripture",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("passage", models.CharField(max_length=255)),
                ("esv", models.TextField(blank=True, null=True)),
                ("kjv", models.TextField(blank=True, null=True)),
                ("rsv", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
