# Generated by Django 4.0.4 on 2022-07-25 01:45

from django.db import migrations


def forward(apps, schema_editor):
    Setting = apps.get_model("office", "Setting")
    initial_settings = Setting.objects.filter(setting_type=1, site=1).exclude(order=0).all()  # MainSettings
    for setting in initial_settings:
        setting.order = setting.order + 1
        setting.save()

    new_setting = Setting.objects.create(
        name="bible_translation",
        title="Bible Translation",
        description="The Bible Translation used for the readings",
        order=1,
        setting_type=1,
        site=1,
    )

    SettingOption = apps.get_model("office", "SettingOption")

    SettingOption.objects.create(
        order=0,
        name="ESV",
        description="English Standard Version, a contemporary language translation",
        value="esv",
        setting=new_setting,
    )

    SettingOption.objects.create(
        order=1,
        name="RSV",
        description="Revised Standard Version, a contemporary language translation with some traditional language",
        value="rsv",
        setting=new_setting,
    )

    SettingOption.objects.create(
        order=2,
        name="KJV",
        description="The King James Version (Authorized Edition), a traditional language translation from 1611",
        value="kjv",
        setting=new_setting,
    )


def backward(apps, schema_editor):
    Setting = apps.get_model("office", "Setting")
    Setting.objects.filter(
        name="bible_translation",
    ).all().delete()

    initial_settings = Setting.objects.filter(setting_type=1, site=1).exclude(order=0).all()  # MainSettings
    for setting in initial_settings:
        setting.order = setting.order - 1
        setting.save()


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0011_scripture"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
