# Generated by Django 4.0.4 on 2022-09-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0012_add_translation_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripture",
            name="nabre",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scripture",
            name="nasb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scripture",
            name="niv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scripture",
            name="nrsvce",
            field=models.TextField(blank=True, null=True),
        ),
    ]
