# Generated by Django 4.0.4 on 2022-10-08 01:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("churchcal", "0011_sanctoralebasedcommemoration_additional_days_after"),
        ("office", "0013_scripture_nabre_scripture_nasb_scripture_niv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectionaryItem",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("service", models.CharField(max_length=255)),
                (
                    "commemoration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="churchcal.commemoration",
                    ),
                ),
                (
                    "common",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.common"
                    ),
                ),
                (
                    "proper",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.proper"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
