# Generated by Django 4.0.4 on 2022-10-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("churchcal", "0011_sanctoralebasedcommemoration_additional_days_after"),
        ("office", "0014_lectionaryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectionaryitem",
            name="sanctorale_commemoration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sanctorale_lectionary_items",
                to="churchcal.sanctoralecommemoration",
            ),
        ),
    ]
