# Generated by Django 4.0.4 on 2022-11-26 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0016_scripture_coverdale_scripture_renewed_coverdale"),
    ]

    def forward(apps, schema_editor):
        Setting = apps.get_model("office", "Setting")

        initial_settings = Setting.objects.filter(setting_type=1, site=1).all()  # MainSettings
        for i, setting in enumerate(initial_settings):
            if setting.order > 0:
                setting.order = setting.order + 1
                setting.save()

        new_setting = Setting.objects.create(
            name="psalm_translation",
            title="Psalms Translation",
            description="The Psalms Translation for use in the Daily Office",
            order=1,
            setting_type=1,
            site=1,
        )

        SettingOption = apps.get_model("office", "SettingOption")

        SettingOption.objects.create(
            order=0,
            name="Contemporary Language",
            description="The New Coverdale Psalter, a contemporary language adaptation of the 1535 Coverdale Psalter, as introducted in the 2019 Book of Common Prayer",
            value="contemporary",
            setting=new_setting,
        )

        SettingOption.objects.create(
            order=1,
            name="Traditional Language",
            description="The Coverdale Psalter, the traditional language psalter from 1535 (with minor edits in 1928), as found in the Traditional Language Edition of the 2019 Book of Common Prayer",
            value="traditional",
            setting=new_setting,
        )

        # ========================

        initial_settings = Setting.objects.filter(setting_type=2, site=1).all()  # Secondary Settings
        for i, setting in enumerate(initial_settings):
            setting.order = setting.order + 1
            setting.save()

        new_setting = Setting.objects.create(
            name="psalm_style",
            title="Psalm Style",
            description="Psalm Recitation Style",
            order=0,
            setting_type=2,
            site=1,
        )

        SettingOption = apps.get_model("office", "SettingOption")

        SettingOption.objects.create(
            order=0,
            name="Antiphonally by Whole Verse",
            description="Alternating between leader and congregation by whole verse",
            value="whole_verse",
            setting=new_setting,
        )

        SettingOption.objects.create(
            order=0,
            name="Antiphonally by Half Verse",
            description="Alternating between leader and congregation by half verse",
            value="half_verse",
            setting=new_setting,
        )

        SettingOption.objects.create(
            order=0,
            name="In Unison",
            description="All verses read in unison",
            value="unison",
            setting=new_setting,
        )

    def backward(apps, schema_editor):
        Setting = apps.get_model("office", "Setting")
        Setting.objects.filter(
            name__in=["psalm_translation", "psalm_style"],
        ).all().delete()

        initial_settings = Setting.objects.filter(setting_type=1, site=1).all()  # MainSettings
        for i, setting in enumerate(initial_settings):
            if setting.order > 1:
                setting.order = setting.order - 1
                setting.save()

        initial_settings = Setting.objects.filter(setting_type=2, site=1).all()  # Secondary Settings
        for i, setting in enumerate(initial_settings):
            setting.order = setting.order - 1
            setting.save()

    operations = [
        migrations.RunPython(forward, backward),
    ]
