# Generated by Django 4.0.4 on 2023-04-02 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0017_add_psalms_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricalCollect",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("collect_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("original_collect", models.TextField(blank=True, max_length=255, null=True)),
                ("normalized_original_collect", models.TextField(blank=True, max_length=255, null=True)),
                ("tune_name", models.CharField(blank=True, max_length=255, null=True)),
                ("first_line", models.CharField(blank=True, max_length=255, null=True)),
                ("pdf_link", models.URLField(blank=True, null=True)),
                ("site_link", models.URLField(blank=True, null=True)),
                ("midi_link", models.URLField(blank=True, null=True)),
                ("lyrics", models.TextField(blank=True, null=True)),
                ("text_source", models.CharField(blank=True, max_length=255, null=True)),
                ("tune_source", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collect",
            name="normalized_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collect",
            name="normalized_traditional_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collect",
            name="metrical_collect",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="office.metricalcollect"
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="metrical_collect_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrical_collect_2",
                to="office.metricalcollect",
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="metrical_collect_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrical_collect_3",
                to="office.metricalcollect",
            ),
        ),
    ]
