# Generated by Django 5.0.2 on 2024-02-18 20:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0018_metricalcollect_collect_normalized_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutitem",
            name="answer",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="collect",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="collect",
            name="traditional_text",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="updatenotice",
            name="notice",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
