# Generated by Django 5.0.2 on 2024-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0019_alter_aboutitem_answer_alter_collect_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="setting_string_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="settingoption",
            name="abbreviation",
            field=models.CharField(default="A", max_length=1),
        ),
    ]
