# Generated by Django 5.2.6 on 2025-12-30 22:52

from django.db import migrations


def forward(apps, schema_editor):
    Setting = apps.get_model("office", "Setting")
    SettingOption = apps.get_model("office", "SettingOption")

    language_setting = Setting.objects.filter(name="language_style").first()
    if language_setting:
        language_setting.title = "Language"
        language_setting.save()

        # Update Contemporary
        contemporary = SettingOption.objects.filter(setting=language_setting, value="contemporary").first()
        if contemporary:
            contemporary.name = "Contemporary English"
            contemporary.save()

        # Update Traditional
        traditional = SettingOption.objects.filter(setting=language_setting, value="traditional").first()
        if traditional:
            traditional.name = "Traditional English"
            traditional.save()

        # Add Spanish
        # Check if it already exists to avoid duplication if migration is re-run partly or manually
        if not SettingOption.objects.filter(setting=language_setting, value="spanish").exists():
            SettingOption.objects.create(
                order=2,
                name="Spanish / Español",
                description="Text in Spanish according to the Libro de Oración Común 2019",
                value="spanish",
                setting=language_setting,
            )


def backward(apps, schema_editor):
    Setting = apps.get_model("office", "Setting")
    SettingOption = apps.get_model("office", "SettingOption")

    language_setting = Setting.objects.filter(name="language_style").first()
    if language_setting:
        language_setting.title = "Language Style"
        language_setting.save()

        # Revert Contemporary
        contemporary = SettingOption.objects.filter(setting=language_setting, value="contemporary").first()
        if contemporary:
            contemporary.name = "Contemporary Language"
            contemporary.save()

        # Revert Traditional
        traditional = SettingOption.objects.filter(setting=language_setting, value="traditional").first()
        if traditional:
            traditional.name = "Traditional Language"
            traditional.save()

        # Remove Spanish
        SettingOption.objects.filter(setting=language_setting, value="spanish").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0020_setting_setting_string_order_and_more"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
