# Generated by Django 5.2.6 on 2025-12-30 23:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0021_auto_20251230_1752"),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="normalized_spanish_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collect",
            name="spanish_text",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
