# Generated by Django 5.2.6 on 2026-01-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0022_collect_normalized_spanish_text_collect_spanish_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripture",
            name="nvi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
