# Generated by Django 5.2.6 on 2026-01-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0024_add_nvi_setting_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="spanish_attribution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="collect",
            name="spanish_subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="collect",
            name="spanish_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="collect",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
