# Generated by Django 6.0.4 on 2026-05-03 23:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def seed_audio_defaults(apps, schema_editor):
    AudioGenerationConfig = apps.get_model("office", "AudioGenerationConfig")
    AudioVoice = apps.get_model("office", "AudioVoice")
    AudioCostRate = apps.get_model("office", "AudioCostRate")

    AudioGenerationConfig.objects.get_or_create(name="default")
    openai_voices = [
        ("leader", "OpenAI Onyx", "onyx", 0),
        ("leader_dialogue", "OpenAI Onyx", "onyx", 0),
        ("congregation", "OpenAI Ash", "ash", 0),
        ("congregation_dialogue", "OpenAI Ash", "ash", 0),
        ("reader", "OpenAI Echo", "echo", 0),
    ]
    for role, name, voice_id, order in openai_voices:
        AudioVoice.objects.get_or_create(
            provider="openai",
            role=role,
            voice_id=voice_id,
            defaults={"name": name, "order": order, "enabled": True},
        )
    AudioCostRate.objects.get_or_create(
        provider="openai",
        model_id="tts-1",
        generation_type="spoken",
        unit="character",
        defaults={
            "usd_per_unit": "0.00001500",
            "notes": "Default fallback estimate; update this rate in admin if pricing changes.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0025_collect_chinese_text_collect_spanish_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioGenerationConfig",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="default", max_length=255, unique=True)),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("elevenlabs_v3", "ElevenLabs v3"),
                            ("elevenlabs_studio", "ElevenLabs Studio"),
                        ],
                        default="openai",
                        max_length=32,
                    ),
                ),
                ("openai_model", models.CharField(default="tts-1", max_length=64)),
                ("openai_output_format", models.CharField(default="mp3", max_length=32)),
                ("elevenlabs_model_id", models.CharField(default="eleven_v3", max_length=64)),
                ("elevenlabs_sound_model_id", models.CharField(default="eleven_v3", max_length=64)),
                ("elevenlabs_output_format", models.CharField(default="mp3_44100_128", max_length=64)),
                ("elevenlabs_language_code", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "elevenlabs_apply_text_normalization",
                    models.CharField(
                        choices=[("auto", "Auto"), ("on", "On"), ("off", "Off")], default="auto", max_length=16
                    ),
                ),
                ("elevenlabs_seed", models.PositiveBigIntegerField(blank=True, null=True)),
                ("elevenlabs_studio_enabled", models.BooleanField(default=False)),
                ("elevenlabs_studio_access_granted", models.BooleanField(default=False)),
                ("elevenlabs_studio_last_checked", models.DateTimeField(blank=True, null=True)),
                ("elevenlabs_studio_last_error", models.TextField(blank=True, null=True)),
                (
                    "sound_default_duration_seconds",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("sound_prompt_influence", models.DecimalField(decimal_places=3, default=0.3, max_digits=4)),
                ("sound_loop", models.BooleanField(default=False)),
                ("spoken_chunk_target_characters", models.PositiveSmallIntegerField(default=1800)),
                ("spoken_chunk_max_characters", models.PositiveSmallIntegerField(default=2000)),
                ("assembly_target_loudness_lufs", models.DecimalField(decimal_places=2, default=-18.0, max_digits=5)),
                ("sound_target_loudness_lufs", models.DecimalField(decimal_places=2, default=-22.0, max_digits=5)),
                ("module_boundary_padding_ms", models.PositiveSmallIntegerField(default=120)),
                ("settings_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AudioCostRate",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=32)),
                ("model_id", models.CharField(max_length=128)),
                ("generation_type", models.CharField(default="spoken", max_length=32)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("character", "Character"),
                            ("cost_unit", "Provider cost unit"),
                            ("minute", "Audio minute"),
                            ("file", "File"),
                        ],
                        default="character",
                        max_length=32,
                    ),
                ),
                ("usd_per_unit", models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ("effective_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("enabled", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-effective_at", "provider", "model_id"),
                "indexes": [
                    models.Index(
                        fields=["provider", "model_id", "generation_type", "enabled", "effective_at"],
                        name="office_audi_provide_0e4224_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AudioGeneratedFile",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("elevenlabs", "ElevenLabs"), ("local", "Local")], max_length=32
                    ),
                ),
                ("provider_mode", models.CharField(default="openai", max_length=32)),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("spoken", "Spoken"),
                            ("sound", "Sound"),
                            ("silence", "Silence"),
                            ("module", "Module"),
                            ("final", "Final"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("disabled", "Disabled"),
                            ("deleted", "Deleted"),
                            ("missing", "Missing"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("cache_key", models.CharField(db_index=True, max_length=128)),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ("text_preview", models.TextField(blank=True, null=True)),
                ("voice_key", models.CharField(blank=True, max_length=512, null=True)),
                ("voices", models.JSONField(blank=True, default=dict)),
                ("model_id", models.CharField(blank=True, max_length=128, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("settings_hash", models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ("settings_snapshot", models.JSONField(blank=True, default=dict)),
                ("office", models.CharField(blank=True, max_length=128, null=True)),
                ("office_date", models.DateField(blank=True, null=True)),
                ("module_name", models.CharField(blank=True, max_length=255, null=True)),
                ("line_type", models.CharField(blank=True, max_length=64, null=True)),
                ("line_id", models.CharField(blank=True, max_length=255, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("media_path", models.CharField(blank=True, max_length=512, null=True)),
                ("duration_seconds", models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ("characters", models.PositiveIntegerField(default=0)),
                ("cost_units", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("cost_source", models.CharField(default="unpriced", max_length=64)),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_mode", "generation_type"], name="office_audi_provide_fd51a1_idx"
                    ),
                    models.Index(fields=["status", "disabled_at", "deleted_at"], name="office_audi_status_e3869b_idx"),
                    models.Index(fields=["office_date", "module_name"], name="office_audi_office__29258d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AudioVoice",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(choices=[("openai", "OpenAI"), ("elevenlabs", "ElevenLabs")], max_length=32),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leader", "Leader"),
                            ("leader_dialogue", "Leader Dialogue"),
                            ("congregation", "Congregation"),
                            ("congregation_dialogue", "Congregation Dialogue"),
                            ("reader", "Reader"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("voice_id", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("provider", "role", "order", "name"),
                "indexes": [
                    models.Index(fields=["provider", "role", "enabled"], name="office_audi_provide_c91614_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="AudioGenerationEvent",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("cache_hit", "Cache hit"),
                            ("cache_skip", "Cache skip"),
                            ("assembled", "Assembled"),
                            ("fallback", "Fallback"),
                            ("health_check", "Health check"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=32, null=True)),
                ("provider_mode", models.CharField(blank=True, max_length=32, null=True)),
                ("generation_type", models.CharField(blank=True, max_length=32, null=True)),
                ("model_id", models.CharField(blank=True, max_length=128, null=True)),
                ("cache_key", models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ("office", models.CharField(blank=True, max_length=128, null=True)),
                ("office_date", models.DateField(blank=True, null=True)),
                ("module_name", models.CharField(blank=True, max_length=255, null=True)),
                ("settings_hash", models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ("characters", models.PositiveIntegerField(default=0)),
                ("cost_units", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "generated_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="office.audiogeneratedfile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_mode", "generation_type"], name="office_audi_provide_abd7de_idx"
                    ),
                    models.Index(fields=["office_date", "module_name"], name="office_audi_office__07de9c_idx"),
                    models.Index(fields=["action", "created"], name="office_audi_action_66e53d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AudioUsage",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("office", models.CharField(blank=True, max_length=128, null=True)),
                ("office_date", models.DateField(blank=True, null=True)),
                ("module_name", models.CharField(blank=True, max_length=255, null=True)),
                ("line_id", models.CharField(blank=True, max_length=255, null=True)),
                ("line_type", models.CharField(blank=True, max_length=64, null=True)),
                ("provider_mode", models.CharField(blank=True, max_length=32, null=True)),
                ("generation_type", models.CharField(blank=True, max_length=32, null=True)),
                ("settings_hash", models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ("settings_snapshot", models.JSONField(blank=True, default=dict)),
                ("start_time_seconds", models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ("duration_seconds", models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ("request_path", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "generated_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_links",
                        to="office.audiogeneratedfile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(fields=["office_date", "module_name"], name="office_audi_office__23df08_idx"),
                    models.Index(fields=["provider_mode", "generation_type"], name="office_audi_provide_3f8b89_idx"),
                ],
            },
        ),
        migrations.RunPython(seed_audio_defaults, migrations.RunPython.noop),
    ]
