# Generated by Django 6.0.4 on 2026-07-18 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0025_collect_chinese_text_collect_spanish_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioClip",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="uuid5 stem / filename base.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("filename", models.CharField(max_length=128)),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Normalized text sent to OpenAI.",
                    ),
                ),
                ("line_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "voice",
                    models.CharField(blank=True, db_index=True, default="", max_length=32),
                ),
                ("model", models.CharField(blank=True, default="", max_length=32)),
                ("speed", models.FloatField(default=1.0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("line", "Single line"),
                            ("group", "Grouped lines"),
                            ("reader", "Reading sentence"),
                            ("silence", "Silence"),
                        ],
                        default="line",
                        max_length=16,
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True,
                        help_text="Length in seconds (via mutagen).",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("line_type", "voice", "text"),
            },
        ),
        migrations.CreateModel(
            name="PronunciationOverride",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match",
                    models.CharField(
                        help_text="Text (or regex) to find in the TTS input before synthesis.",
                        max_length=255,
                    ),
                ),
                (
                    "replacement",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Replacement text.",
                        max_length=255,
                    ),
                ),
                (
                    "is_regex",
                    models.BooleanField(
                        default=False,
                        help_text="Treat 'match' as a regular expression.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Lower numbers are applied first."),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
