# Generated by Django 5.2.6 on 2026-01-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "office",
            "0025_collect_spanish_attribution_collect_spanish_subtitle_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="page_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
