# Generated by Django 6.0.4 on 2026-07-18 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0025_collect_chinese_text_collect_spanish_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioBatchJob",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("job_name", models.CharField(max_length=255, unique=True)),
                ("model_name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("succeeded", "Succeeded"), ("failed", "Failed")],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("chunks", models.JSONField(default=list)),
                ("written", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("last_state", models.CharField(blank=True, default="", max_length=64)),
                ("detail", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
