# Generated by Django 6.0.4 on 2026-07-19 01:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0025_collect_chinese_text_collect_spanish_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "tag_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short label shown in the colored tag (e.g. 'New'). Leave blank to hide the tag.",
                        max_length=40,
                    ),
                ),
                (
                    "tag_color",
                    models.CharField(
                        choices=[
                            ("emerald", "Green"),
                            ("blue", "Blue"),
                            ("amber", "Amber / Yellow"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                            ("gray", "Gray"),
                        ],
                        default="emerald",
                        help_text="Color of the tag.",
                        max_length=20,
                    ),
                ),
                (
                    "text",
                    models.CharField(help_text="The main message text.", max_length=500),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional link destination. Use an internal path (e.g. /calendar) or a full URL (https://...).",
                        max_length=1000,
                    ),
                ),
                (
                    "dismissible",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to dismiss (close) the message.",
                    ),
                ),
                (
                    "dismiss_permanent",
                    models.BooleanField(
                        default=True,
                        help_text="Only applies when the message is dismissible. When checked, a dismissed message stays hidden forever on that device. When unchecked, it reappears on the user's next visit/session.",
                    ),
                ),
                (
                    "show_on_web",
                    models.BooleanField(default=True, help_text="Show this message on the website."),
                ),
                (
                    "show_on_android",
                    models.BooleanField(default=True, help_text="Show this message in the Android app."),
                ),
                (
                    "show_on_ios",
                    models.BooleanField(default=True, help_text="Show this message in the iOS app."),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide the message without deleting it.",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. After this date/time the message will no longer be shown.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, help_text="Lower numbers appear first."),
                ),
            ],
            options={
                "ordering": ["order", "-created"],
            },
        ),
    ]
