# Generated by Django 6.0.4 on 2026-07-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0026_sitemessage"),
        ("office", "0027_seed_pronunciation_overrides"),
    ]

    operations = []
