# Generated by Django 5.2.6 on 2026-10-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0030_order_great_litany_ending"),
        ("office", "0030_pronunciationoverride_providers"),
    ]

    operations = []
