"""Text-to-speech provider adapters for the Daily Office audio pipeline.

The office audio path (normalize -> hash -> reuse-or-generate -> concatenate)
is provider agnostic: it only needs a way to map a liturgical ``line_type`` to
a voice and a way to synthesize a single line to an mp3 on disk. Each backend
(OpenAI, Fish Audio, ...) implements :class:`BaseTTSProvider` so the rest of the
code stays identical regardless of which service is generating audio.

Everything that changes the generated bytes (model, speed, steering, voices)
lives on the provider so the deterministic clip cache key and the ``AudioClip``
bookkeeping rows stay in sync automatically. Switch backends with the
``TTS_PROVIDER`` setting; see ``website/settings.py`` for the env-overridable
model/voice knobs.
"""

import base64
import hashlib
import logging
import os
import random
import re
import time

import requests
from django.conf import settings

logger = logging.getLogger(__name__)


class BaseTTSProvider:
    """Interface shared by every TTS backend.

    Subclasses expose their configuration as properties (read live from Django
    settings so env changes take effect on restart) and implement
    :meth:`synthesize`.
    """

    name = "base"

    @property
    def media_subdir(self):
        """Subfolder under MEDIA_ROOT where this provider's audio is stored.

        Keeping each backend's clips (and concatenated tracks) in their own
        directory makes it trivial to clear just one provider's cache.
        """
        return self.name

    @property
    def model(self):
        """Provider model identifier (stored on AudioClip rows)."""
        raise NotImplementedError

    @property
    def speed(self):
        """Playback speed multiplier applied uniformly to every voice."""
        return 1.0

    @property
    def voices(self):
        """Map of role -> voice id. Keys: leader, congregation, reader, html."""
        raise NotImplementedError

    @property
    def supports_alignment(self):
        """Whether synthesis returns word-level timing metadata."""
        return False

    @property
    def output_sample_rate(self):
        """Sample rate (Hz) of generated clips; silence gaps match this."""
        return 24000

    @property
    def effective_instructions(self):
        """Steering prompt actually sent (empty when unsupported)."""
        return ""

    def role_for_line_type(self, line_type):
        """Map a liturgical line type to its configured speaking role."""
        if not line_type:
            return None
        # "speaker" is an audio-only narration line spoken in the leader voice
        # (it never renders visually); see office/api/views/index.py.
        if "leader" in line_type or "speaker" in line_type:
            return "leader"
        if "congregation" in line_type:
            return "congregation"
        if "html" in line_type or "reader" in line_type:
            return "reader"
        return None

    def voice_for_line_type(self, line_type):
        """Choose a configured voice for a liturgical line type."""
        role = self.role_for_line_type(line_type)
        if not role:
            return None
        configured = self.voices[role]
        if isinstance(configured, (list, tuple)):
            return random.choice(configured) if configured else None
        return configured

    def voice_for_text(self, line_type, text):
        """Choose the voice used to synthesize a specific text block."""
        return self.voice_for_line_type(line_type)

    def cache_signature(self):
        """Everything besides the voice and text that affects the audio bytes.

        Folded into the clip cache key so any config change regenerates clips.
        """
        return f"{self.model} {self.speed} {self.effective_instructions}"

    def pronunciation_locators(self):
        """Optional provider-specific pronunciation dictionary locators."""
        return []

    def synthesize(self, voice, text, file_path):
        """Generate speech for ``text`` in ``voice`` and write mp3 to file_path.

        Returns word timing dictionaries when supported, otherwise an empty
        list. Must raise on failure and must not leave a partial file behind.
        """
        raise NotImplementedError


class OpenAITTSProvider(BaseTTSProvider):
    """OpenAI ``audio.speech`` backend (tts-1 / tts-1-hd / gpt-4o-mini-tts)."""

    name = "openai"
    # Only gpt-4o-mini-tts accepts the `instructions` steering prompt; the
    # tts-1 family ignores it, so we drop it there (and leave it out of the
    # cache signature) to keep hashes consistent with what is actually sent.
    _MODELS_WITHOUT_INSTRUCTIONS = ("tts-1", "tts-1-hd")

    @property
    def media_subdir(self):
        # Versioned subfolder (distinct from the provider name) so newly
        # generated OpenAI clips are isolated from legacy files: the original
        # code wrote clips to the MEDIA_ROOT root and the first refactor used a
        # plain "openai" folder. Both are now orphaned (different voices, model,
        # and line-grouping) and can be deleted without affecting current audio.
        return "openai_v2"

    @property
    def model(self):
        return getattr(settings, "TTS_MODEL", "tts-1")

    @property
    def speed(self):
        return getattr(settings, "TTS_SPEED", 0.95)

    @property
    def output_sample_rate(self):
        # OpenAI TTS returns 24 kHz mono mp3.
        return 24000

    @property
    def voices(self):
        reader = getattr(settings, "TTS_VOICE_READER", "ash")
        return {
            "leader": getattr(settings, "TTS_VOICE_LEADER", "echo"),
            "congregation": getattr(settings, "TTS_VOICE_CONGREGATION", "coral"),
            "reader": reader,
            "html": reader,
        }

    @property
    def effective_instructions(self):
        if self.model in self._MODELS_WITHOUT_INSTRUCTIONS:
            return ""
        return getattr(settings, "TTS_INSTRUCTIONS", "")

    def synthesize(self, voice, text, file_path):
        from openai import OpenAI

        client = OpenAI()
        kwargs = {"model": self.model, "voice": voice, "input": text, "speed": self.speed}
        instructions = self.effective_instructions
        if instructions:
            kwargs["instructions"] = instructions
        response = client.audio.speech.create(**kwargs)
        response.stream_to_file(file_path)
        return []


class ElevenLabsTTSProvider(BaseTTSProvider):
    """ElevenLabs v2/v3 TTS with character alignment grouped into words."""

    name = "elevenlabs"
    ENDPOINT = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/with-timestamps"
    _RETRY_STATUSES = frozenset({429, 500, 502, 503, 504})
    # Documented models the office audio path can send as model_id.
    # IPA/CMU phoneme tags work on eleven_flash_v2; native /IPA/ on eleven_v3.
    # eleven_flash_v2_5 and eleven_multilingual_v2 skip phoneme tags (alias only).
    MODELS = (
        "eleven_multilingual_v2",
        "eleven_flash_v2_5",
        "eleven_flash_v2",
        "eleven_v3",
    )

    @property
    def model(self):
        return getattr(settings, "ELEVENLABS_TTS_MODEL", "eleven_multilingual_v2")

    @property
    def speed(self):
        return getattr(settings, "ELEVENLABS_TTS_SPEED", 1.0)

    @property
    def output_sample_rate(self):
        return 44100

    @property
    def supports_alignment(self):
        return True

    @property
    def voices(self):
        configured_readers = getattr(settings, "ELEVENLABS_TTS_VOICES_READER", ())
        if isinstance(configured_readers, str):
            configured_readers = configured_readers.split(",")
        readers = tuple(voice.strip() for voice in configured_readers if voice.strip())[:10]
        return {
            "leader": getattr(settings, "ELEVENLABS_TTS_VOICE_LEADER", ""),
            "congregation": getattr(settings, "ELEVENLABS_TTS_VOICE_CONGREGATION", ""),
            "reader": readers,
        }

    @property
    def timeout(self):
        return getattr(settings, "ELEVENLABS_TTS_TIMEOUT", 120)

    @property
    def max_retries(self):
        return getattr(settings, "ELEVENLABS_TTS_MAX_RETRIES", 4)

    def cache_signature(self):
        locators = self.pronunciation_locators()
        locator_key = " ".join(
            f"{item.get('pronunciation_dictionary_id', '')}:{item.get('version_id', '')}" for item in locators
        )
        return f"{self.model} {self.speed} {locator_key}"

    def pronunciation_locators(self):
        dictionary_id = getattr(settings, "ELEVENLABS_PRONUNCIATION_DICTIONARY_ID", "")
        if not dictionary_id:
            return []
        locator = {"pronunciation_dictionary_id": dictionary_id}
        version_id = getattr(settings, "ELEVENLABS_PRONUNCIATION_DICTIONARY_VERSION_ID", "")
        if version_id:
            locator["version_id"] = version_id
        return [locator]

    def voice_for_text(self, line_type, text):
        role = self.role_for_line_type(line_type)
        if role != "reader":
            return self.voice_for_line_type(line_type)
        readers = self.voices["reader"]
        if not readers:
            return None
        # Stable pseudo-random assignment keeps repeated serializer passes (the
        # rendered reading and its audio metadata) on the same voice and cache
        # key. Existing DB reuse still wins before this is called.
        digest = hashlib.sha256(text.encode("utf-8")).digest()
        return readers[int.from_bytes(digest[:8], "big") % len(readers)]

    def synthesize(self, voice, text, file_path):
        api_key = getattr(settings, "ELEVENLABS_API_KEY", "")
        if not api_key:
            raise RuntimeError("ELEVENLABS_API_KEY is not configured.")
        if not voice:
            raise RuntimeError("No ElevenLabs voice configured for this role.")

        payload = {
            "text": text,
            "model_id": self.model,
            "voice_settings": {"speed": self.speed},
            "apply_text_normalization": "auto",
        }
        locators = self.pronunciation_locators()
        if locators:
            payload["pronunciation_dictionary_locators"] = locators
        headers = {
            "xi-api-key": api_key,
            "Content-Type": "application/json",
        }
        max_attempts = max(1, self.max_retries + 1)
        for attempt in range(1, max_attempts + 1):
            try:
                response = requests.post(
                    self.ENDPOINT.format(voice_id=voice),
                    params={"output_format": "mp3_44100_128"},
                    json=payload,
                    headers=headers,
                    timeout=self.timeout,
                )
                response.raise_for_status()
                data = response.json()
                audio = base64.b64decode(data["audio_base64"])
                tmp_path = f"{file_path}.part"
                try:
                    with open(tmp_path, "wb") as handle:
                        handle.write(audio)
                    os.replace(tmp_path, file_path)
                except Exception:
                    if os.path.exists(tmp_path):
                        os.remove(tmp_path)
                    raise
                alignment = data.get("alignment") or data.get("normalized_alignment")
                return self.words_from_alignment(alignment)
            except requests.HTTPError as exc:
                status = exc.response.status_code if exc.response is not None else None
                if status not in self._RETRY_STATUSES or attempt >= max_attempts:
                    raise
            except (requests.ConnectionError, requests.Timeout):
                if attempt >= max_attempts:
                    raise

            delay = min(2 ** (attempt - 1), 30)
            logger.warning(
                "ElevenLabs TTS retry (attempt %d/%d) in %ds",
                attempt,
                max_attempts,
                delay,
            )
            time.sleep(delay)

        return []

    @staticmethod
    def words_from_alignment(alignment):
        """Collapse ElevenLabs character alignment into precise word timings."""
        if not alignment:
            return []
        characters = alignment.get("characters") or []
        starts = alignment.get("character_start_times_seconds") or []
        ends = alignment.get("character_end_times_seconds") or []
        if not characters or not (len(characters) == len(starts) == len(ends)):
            return []

        text = "".join(characters)
        words = []
        for match in re.finditer(r"[\w]+(?:[’'][\w]+)*", text, flags=re.UNICODE):
            first = match.start()
            last = match.end() - 1
            words.append(
                {
                    "word": match.group(0),
                    "start_time": starts[first],
                    "end_time": ends[last],
                    "char_start": first,
                    "char_end": match.end(),
                }
            )
        return words


class FishAudioTTSProvider(BaseTTSProvider):
    """Fish Audio backend (https://fish.audio).

    Voices are ``reference_id`` values pointing at voice models in the Fish
    Audio library (browse at https://fish.audio/ or via the ``/model`` API).
    The model is selected with the ``model`` request header; ``s2.1-pro-free``
    is the free developer tier. mp3 output only supports 32 kHz / 44.1 kHz, so
    the default sample rate is 44100.
    """

    name = "fish"
    ENDPOINT = "https://api.fish.audio/v1/tts"
    # Transient HTTP statuses worth retrying: rate limiting plus server errors.
    # 4xx like 400/401/402/422 are permanent (bad key/params) and fail fast.
    _RETRY_STATUSES = frozenset({429, 500, 502, 503, 504})
    # Models that yield interchangeable audio and so should share cached clips.
    # The free and paid tiers of s2.1-pro produce the same voice output, so a
    # clip generated on one must not be regenerated just because the other is
    # configured. Only affects the cache key; the real model header is unchanged.
    _CACHE_MODEL_ALIASES = {"s2.1-pro-free": "s2.1-pro"}

    @property
    def model(self):
        return getattr(settings, "FISH_TTS_MODEL", "s2.1-pro-free")

    def cache_signature(self):
        canonical_model = self._CACHE_MODEL_ALIASES.get(self.model, self.model)
        return f"{canonical_model} {self.speed} {self.effective_instructions}"

    @property
    def speed(self):
        return getattr(settings, "FISH_TTS_SPEED", 0.95)

    @property
    def output_sample_rate(self):
        # mp3 on Fish Audio only supports 32000 or 44100 Hz.
        return getattr(settings, "FISH_TTS_SAMPLE_RATE", 44100)

    @property
    def voices(self):
        reader = getattr(settings, "FISH_TTS_VOICE_READER", "")
        return {
            "leader": getattr(settings, "FISH_TTS_VOICE_LEADER", ""),
            "congregation": getattr(settings, "FISH_TTS_VOICE_CONGREGATION", ""),
            "reader": reader,
            "html": reader,
        }

    @property
    def timeout(self):
        return getattr(settings, "FISH_TTS_TIMEOUT", 120)

    @property
    def max_retries(self):
        """Number of retries after the first attempt (total tries = this + 1)."""
        return getattr(settings, "FISH_TTS_MAX_RETRIES", 4)

    @property
    def backoff_base(self):
        """Base seconds for exponential backoff (doubled each retry)."""
        return getattr(settings, "FISH_TTS_BACKOFF_BASE", 1.0)

    @property
    def backoff_max(self):
        """Cap (seconds) on a single backoff wait."""
        return getattr(settings, "FISH_TTS_BACKOFF_MAX", 30.0)

    def _api_key(self):
        # `FISH_AUDIO_API_KEY` is canonical; fall back to the historical
        # `FISH_AUDIO_AI_KEY` spelling so existing env files keep working.
        return getattr(settings, "FISH_AUDIO_API_KEY", "") or getattr(settings, "FISH_AUDIO_AI_KEY", "")

    def synthesize(self, voice, text, file_path):
        api_key = self._api_key()
        if not api_key:
            raise RuntimeError("FISH_AUDIO_API_KEY is not configured.")
        if not voice:
            raise RuntimeError("No Fish Audio reference_id configured for this voice.")
        payload = {
            "text": text,
            "reference_id": voice,
            "format": "mp3",
            "mp3_bitrate": getattr(settings, "FISH_TTS_MP3_BITRATE", 128),
            "sample_rate": self.output_sample_rate,
            "prosody": {"speed": self.speed},
            "normalize": True,
            "latency": "normal",
        }
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "model": self.model,
        }
        # Retry transient failures (rate limits, 5xx, connection/timeout) with
        # exponential backoff + jitter. Permanent errors (bad key/params) raise
        # on the first attempt so we don't waste time or hammer the API.
        max_attempts = max(1, self.max_retries + 1)
        for attempt in range(1, max_attempts + 1):
            try:
                self._synthesize_once(payload, headers, file_path)
                return
            except requests.HTTPError as exc:
                status = exc.response.status_code if exc.response is not None else None
                if status not in self._RETRY_STATUSES or attempt >= max_attempts:
                    raise
                retry_after = self._parse_retry_after(exc.response)
                delay = self._backoff_delay(attempt, retry_after)
                logger.warning(
                    "Fish Audio TTS %s (attempt %d/%d); retrying in %.1fs",
                    status,
                    attempt,
                    max_attempts,
                    delay,
                )
                time.sleep(delay)
            except (requests.ConnectionError, requests.Timeout, requests.exceptions.ChunkedEncodingError) as exc:
                if attempt >= max_attempts:
                    raise
                delay = self._backoff_delay(attempt, None)
                logger.warning(
                    "Fish Audio TTS network error %s (attempt %d/%d); retrying in %.1fs",
                    exc.__class__.__name__,
                    attempt,
                    max_attempts,
                    delay,
                )
                time.sleep(delay)

    def _synthesize_once(self, payload, headers, file_path):
        """One synthesis attempt. Streams to a sidecar temp file and atomically
        renames so a failed or interrupted request never leaves a truncated mp3
        that would be treated as a valid cached clip."""
        tmp_path = f"{file_path}.part"
        try:
            with requests.post(
                self.ENDPOINT, json=payload, headers=headers, stream=True, timeout=self.timeout
            ) as response:
                response.raise_for_status()
                with open(tmp_path, "wb") as handle:
                    for chunk in response.iter_content(chunk_size=8192):
                        if chunk:
                            handle.write(chunk)
            os.replace(tmp_path, file_path)
        except Exception:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            raise

    def _backoff_delay(self, attempt, retry_after):
        """Seconds to wait before the next attempt. Honors a server-provided
        Retry-After; otherwise exponential backoff (base * 2^(attempt-1)) capped
        at backoff_max, with up to 25% jitter to avoid thundering herds."""
        if retry_after is not None:
            return min(float(retry_after), self.backoff_max)
        delay = min(self.backoff_base * (2 ** (attempt - 1)), self.backoff_max)
        return delay + random.uniform(0, delay * 0.25)

    @staticmethod
    def _parse_retry_after(response):
        """Parse a Retry-After header expressed in seconds; ignore HTTP-date
        forms (rare here) and fall back to computed backoff for those."""
        if response is None:
            return None
        value = response.headers.get("Retry-After")
        if not value:
            return None
        try:
            return max(0.0, float(value))
        except (TypeError, ValueError):
            return None


_PROVIDERS = {
    OpenAITTSProvider.name: OpenAITTSProvider,
    ElevenLabsTTSProvider.name: ElevenLabsTTSProvider,
    FishAudioTTSProvider.name: FishAudioTTSProvider,
}


def provider_names():
    """Registered provider names (also their MEDIA_ROOT subfolder names)."""
    return sorted(_PROVIDERS)


def get_tts_provider(name=None):
    """Return the active TTS provider instance.

    ``name`` overrides the ``TTS_PROVIDER`` setting (defaults to ``openai``).
    """
    if name is None:
        name = getattr(settings, "TTS_PROVIDER", "openai")
    provider_cls = _PROVIDERS.get((name or "").lower())
    if provider_cls is None:
        valid = ", ".join(sorted(_PROVIDERS))
        raise ValueError(f"Unknown TTS_PROVIDER {name!r}. Valid options: {valid}.")
    return provider_cls()
