import os
import time
from django.core.management.base import BaseCommand
from django.conf import settings
from mutagen.mp3 import MP3
from mutagen.id3 import ID3NoHeaderError


class Command(BaseCommand):
    help = "Finds and optionally deletes 'full' office audio files generated by ffmpeg."

    def add_arguments(self, parser):
        parser.add_argument(
            "--execute",
            action="store_true",
            help="Actually delete the files. Without this, it runs in dry-run mode.",
        )
        parser.add_argument(
            "--days",
            type=int,
            default=0,
            help="Minimum age in days of the files to delete (default: 0).",
        )

    def handle(self, *args, **options):
        is_dry_run = not options["execute"]
        days_old = options["days"]
        media_root = settings.MEDIA_ROOT

        cutoff_time = time.time() - (days_old * 86400)

        if is_dry_run:
            self.stdout.write(
                self.style.WARNING(f"Running in DRY-RUN mode. Looking for files older than {days_old} days.")
            )
        else:
            self.stdout.write(
                self.style.ERROR(f"Running in EXECUTE mode. Files older than {days_old} days WILL be deleted.")
            )

        if not os.path.exists(media_root):
            self.stdout.write(self.style.ERROR(f"Media root does not exist: {media_root}"))
            return

        full_files_found = []
        total_size_bytes = 0
        total_mp3s = 0

        for filename in os.listdir(media_root):
            if not filename.endswith(".mp3"):
                continue

            file_path = os.path.join(media_root, filename)

            # Check file age
            if os.path.getmtime(file_path) >= cutoff_time:
                continue

            total_mp3s += 1

            try:
                audio = MP3(file_path)
                # Check ID3 tags for ffmpeg/Lavf signature
                is_ffmpeg = False
                if audio.tags:
                    # TSSE is the 'Software/Hardware and settings used for encoding' frame
                    tsse_tags = audio.tags.getall("TSSE")
                    for tag in tsse_tags:
                        if "Lavf" in str(tag.text) or "ffmpeg" in str(tag.text).lower():
                            is_ffmpeg = True
                            break

                if is_ffmpeg:
                    size = os.path.getsize(file_path)
                    full_files_found.append((filename, size))
                    total_size_bytes += size

                    if is_dry_run:
                        self.stdout.write(f"Found full file: {filename} ({size / 1024 / 1024:.2f} MB)")
                    else:
                        os.remove(file_path)
                        self.stdout.write(self.style.SUCCESS(f"Deleted: {filename}"))

            except ID3NoHeaderError:
                # File has no ID3 tags, likely a raw OpenAI file
                pass
            except Exception as e:
                self.stdout.write(self.style.ERROR(f"Error reading {filename}: {e}"))

        self.stdout.write("\n" + "=" * 40)
        self.stdout.write(self.style.SUCCESS(f"Total MP3s scanned (older than {days_old} days): {total_mp3s}"))
        self.stdout.write(self.style.SUCCESS(f"Full office files identified: {len(full_files_found)}"))
        self.stdout.write(
            self.style.SUCCESS(f"Total space used by full files: {total_size_bytes / 1024 / 1024:.2f} MB")
        )

        if is_dry_run:
            self.stdout.write(self.style.WARNING("This was a dry run. Run with --execute to delete the files."))
