import os
import time

from django.conf import settings
from django.core.management.base import BaseCommand
from mutagen.id3 import ID3NoHeaderError
from mutagen.mp3 import MP3

from office.api.views.tts import get_tts_provider, provider_names


class Command(BaseCommand):
    help = "Finds and optionally deletes 'full' office audio files generated by ffmpeg."

    def add_arguments(self, parser):
        parser.add_argument(
            "--execute",
            action="store_true",
            help="Actually delete the files. Without this, it runs in dry-run mode.",
        )
        parser.add_argument(
            "--days",
            type=int,
            default=0,
            help="Minimum age in days of the files to delete (default: 0).",
        )

    def _scan_dirs(self, media_root):
        """MEDIA_ROOT plus each TTS provider media subfolder (e.g. openai_v2/, fish/)."""
        dirs = [media_root]
        for name in provider_names():
            subdir = get_tts_provider(name).media_subdir
            path = os.path.join(media_root, subdir)
            if path not in dirs and os.path.isdir(path):
                dirs.append(path)
        return dirs

    def _is_ffmpeg_full_track(self, audio):
        if not audio.tags:
            return False
        # TSSE is the 'Software/Hardware and settings used for encoding' frame
        for tag in audio.tags.getall("TSSE"):
            text = str(tag.text)
            if "Lavf" in text or "ffmpeg" in text.lower():
                return True
        return False

    def handle(self, *args, **options):
        is_dry_run = not options["execute"]
        days_old = options["days"]
        media_root = settings.MEDIA_ROOT

        cutoff_time = time.time() - (days_old * 86400)

        if is_dry_run:
            self.stdout.write(
                self.style.WARNING(f"Running in DRY-RUN mode. Looking for files older than {days_old} days.")
            )
        else:
            self.stdout.write(
                self.style.ERROR(f"Running in EXECUTE mode. Files older than {days_old} days WILL be deleted.")
            )

        if not os.path.exists(media_root):
            self.stdout.write(self.style.ERROR(f"Media root does not exist: {media_root}"))
            return

        scan_dirs = self._scan_dirs(media_root)
        self.stdout.write(f"Scanning: {', '.join(scan_dirs)}")

        full_files_found = []
        total_size_bytes = 0
        total_mp3s = 0

        for scan_dir in scan_dirs:
            for filename in os.listdir(scan_dir):
                if not filename.endswith(".mp3"):
                    continue

                file_path = os.path.join(scan_dir, filename)
                if not os.path.isfile(file_path):
                    continue

                # Check file age
                if os.path.getmtime(file_path) >= cutoff_time:
                    continue

                total_mp3s += 1
                display_name = os.path.relpath(file_path, media_root)

                try:
                    audio = MP3(file_path)
                    if not self._is_ffmpeg_full_track(audio):
                        continue

                    size = os.path.getsize(file_path)
                    full_files_found.append((display_name, size))
                    total_size_bytes += size

                    if is_dry_run:
                        self.stdout.write(f"Found full file: {display_name} ({size / 1024 / 1024:.2f} MB)")
                    else:
                        os.remove(file_path)
                        self.stdout.write(self.style.SUCCESS(f"Deleted: {display_name}"))

                except ID3NoHeaderError:
                    # File has no ID3 tags, likely a raw TTS clip
                    pass
                except Exception as e:
                    # If mutagen can't sync to MPEG frame, it's likely a corrupted or empty file
                    if "can't sync to MPEG frame" in str(e):
                        size = os.path.getsize(file_path)
                        self.stdout.write(
                            self.style.WARNING(f"Found corrupted/invalid MP3 file: {display_name} ({size} bytes)")
                        )
                        if not is_dry_run:
                            os.remove(file_path)
                            self.stdout.write(self.style.SUCCESS(f"Deleted corrupted/invalid file: {display_name}"))
                    else:
                        self.stdout.write(self.style.ERROR(f"Error reading {display_name}: {e}"))

        self.stdout.write("\n" + "=" * 40)
        self.stdout.write(self.style.SUCCESS(f"Total MP3s scanned (older than {days_old} days): {total_mp3s}"))
        self.stdout.write(self.style.SUCCESS(f"Full office files identified: {len(full_files_found)}"))
        self.stdout.write(
            self.style.SUCCESS(f"Total space used by full files: {total_size_bytes / 1024 / 1024:.2f} MB")
        )

        if is_dry_run:
            self.stdout.write(self.style.WARNING("This was a dry run. Run with --execute to delete the files."))
