# Generated by Django 2.2.6 on 2019-10-15 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Psalm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField(unique=True)),
                ("latin_title", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PsalmVerse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField()),
                ("first_half", models.CharField(max_length=1000)),
                ("second_half", models.CharField(max_length=1000)),
                ("psalm", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="psalter.Psalm")),
            ],
            options={"unique_together": {("psalm", "number")}},
        ),
    ]
