# Generated by Django 3.0.6 on 2020-05-24 22:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psalter', '0002_psalmtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psalmtopic',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='psalmtopic',
            old_name='psalm',
            new_name='psalms',
        ),
        migrations.CreateModel(
            name='PsalmTopicPsalm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('psalm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psalter.Psalm')),
                ('psalm_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psalter.PsalmTopic')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
