# Generated by Django 4.0.4 on 2022-07-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psalter", "0004_migrate_psalm_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="psalmverse",
            name="first_half_tle",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="psalmverse",
            name="second_half_tle",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
