# Generated by Django 6.0.4 on 2026-07-19 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("office_view", "Office view"),
                            ("audio_play", "Audio play (confirmed)"),
                            ("audio_loaded", "Audio loaded (approx.)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("office", "Daily Office"),
                            ("family", "Family Prayer"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "office",
                    models.CharField(blank=True, db_index=True, default="", max_length=50),
                ),
                ("office_date", models.DateField(blank=True, null=True)),
                (
                    "client_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("electron", "Electron"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("browser", models.CharField(blank=True, default="", max_length=50)),
                ("os", models.CharField(blank=True, default="", max_length=50)),
                (
                    "translation",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "created"],
                        name="analytics_a_event_t_1b53f8_idx",
                    ),
                    models.Index(
                        fields=["office", "created"],
                        name="analytics_a_office_4e0948_idx",
                    ),
                ],
            },
        ),
    ]
