# Generated by Django 6.0.4 on 2026-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
