# Generated by Django 3.1.4 on 2021-02-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standrew", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieballot",
            name="likelihood_of_coming",
            field=models.IntegerField(
                choices=[
                    (100, "I plan to come"),
                    (75, "I will most likely come"),
                    (50, "I'm not sure (greater than 50/50 chance at this point)"),
                ],
                default=-1,
            ),
        ),
        migrations.AddField(
            model_name="moviecandidate",
            name="likelihood_of_coming",
            field=models.IntegerField(
                choices=[
                    (100, "I plan to come"),
                    (75, "I will probably come"),
                    (50, "50/50 at this point"),
                    (25, "I most likely won't come"),
                    (0, "I do not plan to come"),
                    (-1, "Not Answered"),
                ],
                default=-1,
            ),
        ),
        migrations.AddField(
            model_name="moviecandidate",
            name="recommended_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
