# Generated by Django 3.1.4 on 2021-03-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standrew", "0003_auto_20210225_0933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviedetails",
            name="movie_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
