# Generated by Django 5.1.4 on 2025-02-02 03:27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standrew", "0005_movienight_movie_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleStudyDay",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "jesus_story_book_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "jesus_story_book_title",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("jesus_story_book_summary", models.TextField(blank=True, null=True)),
                ("jesus_story_book_content", models.TextField(blank=True, null=True)),
                (
                    "passage_title",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("sermon", models.TextField(blank=True, null=True)),
                ("intersection", models.TextField(blank=True, null=True)),
                (
                    "study_questions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "practical_questions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("reflection", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BibleStudyPassage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("passage", models.CharField(max_length=256)),
                ("text", models.TextField(blank=True, null=True)),
                ("html", models.TextField(blank=True, null=True)),
                (
                    "headings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "extracted_headings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("theme", models.TextField(blank=True, null=True)),
                ("four_senses", models.JSONField(blank=True, null=True)),
                ("background", models.TextField(blank=True, null=True)),
                ("primary_sources", models.JSONField(blank=True, null=True)),
                ("interesting_points", models.TextField(blank=True, null=True)),
                (
                    "study_questions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "practical_questions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("reflection", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BibleStudyDayPassage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "bible_study_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standrew.biblestudyday",
                    ),
                ),
                (
                    "bible_study_passage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standrew.biblestudypassage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
