# Generated by Django 5.1.4 on 2025-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standrew", "0006_biblestudyday_biblestudypassage_biblestudydaypassage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biblestudyday",
            name="sermon",
        ),
        migrations.AddField(
            model_name="biblestudyday",
            name="quote",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biblestudypassage",
            name="primary_verse",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
