# Generated by Django 2.1.5 on 2019-09-26 02:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("year", models.CharField(max_length=256)),
                ("abbreviation", models.CharField(max_length=256)),
                ("google_sheet_id", models.CharField(max_length=256)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Commemoration",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("color", models.CharField(blank=True, max_length=256, null=True)),
                ("additional_color", models.CharField(blank=True, max_length=256, null=True)),
                ("alternate_color", models.CharField(blank=True, max_length=256, null=True)),
                ("alternate_color_2", models.CharField(blank=True, max_length=256, null=True)),
                ("collect", models.TextField(blank=True, null=True)),
                ("alternate_collect", models.TextField(blank=True, null=True)),
                ("eve_collect", models.TextField(blank=True, null=True)),
                ("color_notes", models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CommemorationRank",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("formatted_name", models.CharField(max_length=256)),
                (
                    "precedence_rank",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("calendar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="churchcal.Calendar")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Denomination",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("abbreviation", models.CharField(max_length=256)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Proper",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                            (24, 24),
                            (25, 25),
                            (26, 26),
                            (27, 27),
                            (28, 28),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("collect", models.TextField(blank=True, null=True)),
                ("calendar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="churchcal.Calendar")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                            (24, 24),
                            (25, 25),
                            (26, 26),
                            (27, 27),
                            (28, 28),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("color", models.CharField(max_length=255)),
                ("alternate_color", models.CharField(blank=True, max_length=255, null=True)),
                ("calendar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="churchcal.Calendar")),
                (
                    "rank",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="churchcal.CommemorationRank"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="FerialCommemoration",
            fields=[
                (
                    "commemoration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="churchcal.Commemoration",
                    ),
                )
            ],
            options={"managed": False},
            bases=("churchcal.commemoration",),
        ),
        migrations.CreateModel(
            name="SanctoraleBasedCommemoration",
            fields=[
                (
                    "commemoration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="churchcal.Commemoration",
                    ),
                ),
                ("weekday", models.CharField(max_length=256)),
                ("number_after", models.SmallIntegerField()),
                ("month_after", models.PositiveSmallIntegerField()),
                ("day_after", models.PositiveSmallIntegerField()),
            ],
            options={"abstract": False},
            bases=("churchcal.commemoration",),
        ),
        migrations.CreateModel(
            name="SanctoraleCommemoration",
            fields=[
                (
                    "commemoration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="churchcal.Commemoration",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
            ],
            options={"abstract": False},
            bases=("churchcal.commemoration",),
        ),
        migrations.CreateModel(
            name="TemporaleCommemoration",
            fields=[
                (
                    "commemoration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="churchcal.Commemoration",
                    ),
                ),
                ("days_after_easter", models.SmallIntegerField()),
            ],
            options={"abstract": False},
            bases=("churchcal.commemoration",),
        ),
        migrations.AddField(
            model_name="season",
            name="start_commemoration",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.Commemoration"
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="calendar",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="churchcal.Calendar"),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="cannot_occur_after",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.Commemoration"
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="rank",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.CommemorationRank"
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="denomination",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.Denomination"
            ),
        ),
    ]
