# Generated by Django 2.2.6 on 2019-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("churchcal", "0001_initial")]

    operations = [
        migrations.AddField(model_name="commemoration", name="link_1", field=models.URLField(blank=True, null=True)),
        migrations.AddField(model_name="commemoration", name="link_2", field=models.URLField(blank=True, null=True)),
        migrations.AddField(model_name="commemoration", name="link_3", field=models.URLField(blank=True, null=True)),
        migrations.AddField(
            model_name="sanctoralecommemoration",
            name="saint_fill_in_the_blank",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="sanctoralecommemoration",
            name="saint_gender",
            field=models.CharField(
                blank=True, choices=[("M", "Male"), ("F", "Female"), ("P", "Plural")], max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="sanctoralecommemoration",
            name="saint_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="sanctoralecommemoration",
            name="saint_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASTOR", "OF A PASTOR"),
                    ("MONASTIC", "OF A MONASTIC OR RELIGIOUS"),
                    ("MARTYR", "OF A MARTYR"),
                    ("MISSIONARY", "OF A MISSIONARY OR EVANGELIST"),
                    ("TEACHER", "OF A TEACHER OF THE FAITH"),
                    ("RENEWER", "OF A RENEWER OF SOCIETY"),
                    ("REFORMER", "OF A REFORMER OF THE CHURCH"),
                    ("SAINT_1", "OF ANY COMMEMORATION 1"),
                    ("SAINT_2", "OF ANY COMMEMORATION 2"),
                    ("ECUMENIST", "OF AN ECUMENIST"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
