# Generated by Django 2.2.8 on 2020-03-30 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("churchcal", "0002_auto_20191022_1317")]

    operations = [
        migrations.CreateModel(
            name="Common",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("abbreviation", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("collect", models.TextField(blank=True, null=True)),
                ("alternate_collect", models.TextField(blank=True, null=True)),
                ("calendar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="churchcal.Calendar")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="MassReading",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("long_citation", models.CharField(max_length=256)),
                ("long_text", models.TextField(blank=True, null=True)),
                ("service", models.CharField(max_length=256)),
                ("short_citation", models.CharField(max_length=256)),
                ("short_text", models.TextField(blank=True, null=True)),
                ("years", models.CharField(max_length=3)),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("prophecy", "prophecy"),
                            ("psalm", "psalm"),
                            ("epistle", "epistle"),
                            ("gospel", "gospel"),
                        ],
                        max_length=256,
                    ),
                ),
                ("book", models.CharField(max_length=256)),
                ("testament", models.CharField(max_length=4)),
                ("abbreviation", models.CharField(blank=True, max_length=256, null=True)),
                ("reading_number", models.PositiveSmallIntegerField()),
                ("order", models.PositiveSmallIntegerField()),
                ("calendar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="churchcal.Calendar")),
                (
                    "commemoration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="churchcal.Commemoration",
                    ),
                ),
                (
                    "common",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.Common"
                    ),
                ),
                (
                    "proper",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.Proper"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
