# Generated by Django 3.1.4 on 2021-01-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchcal", "0003_common_massreading"),
    ]

    operations = [
        migrations.AddField(
            model_name="commemoration",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
    ]
