# Generated by Django 3.1.4 on 2021-01-17 22:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("churchcal", "0004_commemoration_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commemoration",
            name="biography",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
