# Generated by Django 3.1.4 on 2021-01-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchcal", "0005_auto_20210117_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="commemoration",
            name="image_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
