# Generated by Django 4.0.4 on 2022-07-31 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0009_add_trad_language_setting"),
        ("churchcal", "0006_commemoration_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="commemoration",
            name="collect_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commemoration_collect_1",
                to="office.collect",
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="collect_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commemoration_collect_2",
                to="office.collect",
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="collect_eve",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commemoration_collect_eve",
                to="office.collect",
            ),
        ),
        migrations.AddField(
            model_name="common",
            name="collect_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_collect_1",
                to="office.collect",
            ),
        ),
        migrations.AddField(
            model_name="common",
            name="collect_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_collect_2",
                to="office.collect",
            ),
        ),
        migrations.AddField(
            model_name="proper",
            name="collect_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proper_collect_1",
                to="office.collect",
            ),
        ),
    ]
