# Generated by Django 4.0.4 on 2022-07-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("churchcal", "0007_commemoration_collect_1_commemoration_collect_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="common",
            name="collect_format_string",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="common",
            name="collect_tle_format_string",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="sanctoralecommemoration",
            name="common",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="churchcal.common"
            ),
        ),
    ]
