# Generated by Django 4.0.4 on 2022-08-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("churchcal", "0008_common_collect_format_string_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commemoration",
            name="alternate_collect",
        ),
        migrations.RemoveField(
            model_name="commemoration",
            name="collect",
        ),
        migrations.RemoveField(
            model_name="commemoration",
            name="eve_collect",
        ),
        migrations.RemoveField(
            model_name="common",
            name="alternate_collect",
        ),
        migrations.RemoveField(
            model_name="common",
            name="collect",
        ),
        migrations.RemoveField(
            model_name="proper",
            name="collect",
        ),
    ]
