# Generated by Django 4.0.4 on 2022-08-24 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0012_add_translation_setting"),
        ("churchcal", "0009_remove_commemoration_alternate_collect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="massreading",
            name="long_scripture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="long_scripture",
                to="office.scripture",
            ),
        ),
        migrations.AddField(
            model_name="massreading",
            name="short_scripture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="short_scripture",
                to="office.scripture",
            ),
        ),
    ]
