# Generated by Django 4.0.4 on 2022-10-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churchcal", "0010_massreading_long_scripture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctoralebasedcommemoration",
            name="additional_days_after",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
