# Generated by Django 5.0.2 on 2024-02-18 20:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("churchcal", "0011_sanctoralebasedcommemoration_additional_days_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commemoration",
            name="biography",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
