# Generated by Django 5.1.4 on 2025-02-24 03:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchcal", "0012_alter_commemoration_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="commemoration",
            name="ai_bullet_points",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_bullet_points_citations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_butler",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_foods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_foods_citations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_hagiography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_hagiography_citations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_legend",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_legend_citations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_lesser_feasts_and_fasts",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_martyrology",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_one_sentence",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_quote",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_quote_by",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_quote_citations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_traditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_traditions_citations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_verse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commemoration",
            name="ai_verse_citation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
