# Generated by Django 5.1.4 on 2025-03-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "churchcal",
            "0014_commemoration_ai_image_1_commemoration_ai_image_2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commemoration",
            name="ai_image_1",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="commemoration",
            name="ai_image_2",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
