# Generated by Django 5.2.6 on 2025-12-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchcal", "0015_alter_commemoration_ai_image_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="common",
            name="collect_spanish_format_string",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
