# Generated by Django 6.0.4 on 2026-07-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchcal", "0015_alter_commemoration_ai_image_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commemoration",
            name="ai_generation_instructions",
            field=models.TextField(
                blank=True,
                help_text="Extra instructions appended to every AI regeneration prompt for this feast (e.g. do not confuse with another saint).",
                null=True,
            ),
        ),
    ]
