# Generated by Django 4.0.4 on 2023-04-02 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hymn",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("hymnal", models.CharField(blank=True, max_length=255, null=True)),
                ("number", models.CharField(blank=True, max_length=10, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("tune_name", models.CharField(blank=True, max_length=255, null=True)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="hymnal/hymns/pdf")),
                ("mp3", models.FileField(blank=True, null=True, upload_to="hymnal/hymns/mp3")),
                ("lyrics", models.TextField(blank=True, null=True)),
                ("copyright", models.TextField(blank=True, null=True)),
                ("fair_use", models.BooleanField(default=False)),
                ("rite_planning_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
