# Generated by Django 2.2.3 on 2019-08-02 02:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sermon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Sermon Title", max_length=255, verbose_name="Sermon title")),
                (
                    "location",
                    models.CharField(
                        help_text="Location Sermon was delivered", max_length=255, verbose_name="Location"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="The sermon in Microsoft Word or text format",
                        null=True,
                        upload_to="",
                        verbose_name="File",
                    ),
                ),
                ("text", models.TextField(help_text="The full content of the sermon", verbose_name="Text")),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="A summary of the sermon", null=True, verbose_name="Summary"
                    ),
                ),
                (
                    "auto_summary",
                    models.TextField(
                        blank=True,
                        help_text="An auto-generated summary of the sermon",
                        null=True,
                        verbose_name="Auto-summary",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Publicly displayed Notes", null=True, verbose_name="Notes"
                    ),
                ),
                (
                    "private_notes",
                    models.TextField(
                        blank=True, help_text="Notes (Internal only)", null=True, verbose_name="Notes (private)"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SermonDateTime",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "date_and_time_give",
                    models.DateTimeField(help_text="Date and Time Given", verbose_name="Date Given"),
                ),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sermons.Sermon", verbose_name="Sermon"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
