# Generated by Django 2.2.3 on 2019-08-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sermons", "0003_sermon_content")]

    operations = [
        migrations.RenameField(
            model_name="sermondatetime", old_name="date_and_time_give", new_name="date_and_time_given"
        ),
        migrations.AddField(
            model_name="sermon",
            name="primary_date_and_time_given",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and Time Given",
                null=True,
                verbose_name="The primary date given (used for sorting).  More than one date and time can be added on the date and time tab",
            ),
        ),
    ]
