# Generated by Django 2.2.3 on 2019-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sermons", "0005_auto_20190808_0252")]

    operations = [
        migrations.AddField(
            model_name="sermondatetime",
            name="primary",
            field=models.BooleanField(
                default=False,
                help_text="Should this date be the primary date used for sorting?",
                verbose_name="Primray Service",
            ),
        )
    ]
