# Generated by Django 2.2.4 on 2019-09-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("sermons", "0008_auto_20190907_2234")]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="location",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sermons.SermonLocation"
            ),
        ),
        migrations.AlterField(
            model_name="sermonbiblepassage",
            name="type",
            field=models.IntegerField(
                choices=[
                    (2, "PSALM"),
                    (1, "PROPHECY (or other Old Testament)"),
                    (5, "OTHER"),
                    (3, "EPISTLE (or Acts / Revelation)"),
                    (4, "GOSPEL"),
                ],
                default=0,
            ),
        ),
    ]
