# Generated by Django 2.2.4 on 2019-09-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sermons", "0009_auto_20190907_2301")]

    operations = [
        migrations.AlterField(
            model_name="sermonbiblepassage",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "PROPHECY (or other Old Testament)"),
                    (2, "PSALM"),
                    (4, "GOSPEL"),
                    (3, "EPISTLE (or Acts / Revelation)"),
                    (5, "OTHER"),
                ],
                default=0,
            ),
        )
    ]
