# Generated by Django 2.2.4 on 2019-09-08 01:45

import array_tags.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sermons", "0010_auto_20190907_2311")]

    operations = [
        migrations.AlterField(
            model_name="sermonbiblepassage",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "PROPHECY (or other Old Testament)"),
                    (3, "EPISTLE (or Acts / Revelation)"),
                    (2, "PSALM"),
                    (5, "OTHER"),
                    (4, "GOSPEL"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sermonlocation",
            name="alternate_names",
            field=array_tags.fields.TagField(
                base_field=models.CharField(max_length=50),
                blank=True,
                help_text="A list of strings to be matched when importing a sermon.",
                null=True,
                size=None,
            ),
        ),
    ]
