// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAffix: typeof import('element-plus/es')['ElAffix']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
}
export {}
