"""Audio-only office framing; recorded bells are never generated by TTS.

Bell sources supplied by Benjamin: traian1984-church-bell-273815.mp3
(eight-second excerpt with a three-second fade) and
universfield-single-church-bell-2-352062.mp3 (single strike with its decay).
Both are mono 44.1 kHz MP3s, reduced in volume for spoken-prayer playback.
"""

import hashlib
import os
import tempfile
from pathlib import Path

from django.conf import settings

INTERCESSION_INVITATION = "Let us unite our prayers and thanksgivings with those of the whole church."
INTERCESSION_MODULE = "Intercessions, Thanksgivings, and Praise"


def spoken_day(day):
    """Spell out calendar ordinals so TTS cannot read them as cardinal numbers."""
    ordinals = (
        "first",
        "second",
        "third",
        "fourth",
        "fifth",
        "sixth",
        "seventh",
        "eighth",
        "ninth",
        "tenth",
        "eleventh",
        "twelfth",
        "thirteenth",
        "fourteenth",
        "fifteenth",
        "sixteenth",
        "seventeenth",
        "eighteenth",
        "nineteenth",
        "twentieth",
        "twenty-first",
        "twenty-second",
        "twenty-third",
        "twenty-fourth",
        "twenty-fifth",
        "twenty-sixth",
        "twenty-seventh",
        "twenty-eighth",
        "twenty-ninth",
        "thirtieth",
        "thirty-first",
    )
    return ordinals[day - 1]


def announcement(office):
    evening = office.name in {
        "Evening Prayer",
        "Compline",
        "Family Prayer in the Early Evening",
        "Family Prayer at the Close of Day",
    }
    commemorations = office.date.all_evening if evening else office.date.all
    names = " and ".join(commemoration.name for commemoration in commemorations)
    name = {"Morning Prayer": "Daily Morning Prayer", "Evening Prayer": "Daily Evening Prayer"}.get(
        office.name, office.name
    )
    day = office.date.date
    return f"{name} for {day:%A}, {day:%B} {spoken_day(day.day)}, {day.year}: {names}."


def bell_track(asset, module, identifier, base_url, before=0, after=0):
    data = (Path(__file__).parent / "audio_assets" / f"{asset}.mp3").read_bytes()
    filename = f"gemini/{asset}_{hashlib.sha256(data).hexdigest()[:16]}.mp3"
    target = Path(settings.MEDIA_ROOT) / filename
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.stat().st_size != len(data):
        with tempfile.NamedTemporaryFile(dir=target.parent, delete=False) as handle:
            temporary = handle.name
            handle.write(data)
        try:
            os.replace(temporary, target)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
    return {
        "line_id": identifier,
        "module": module,
        "text": "",
        "word_timing": [],
        "path": settings.MEDIA_URL + filename,
        "url": f"{base_url}/api/v1/audio_track/{filename}",
        "silence_before": before,
        "silence_after": after,
        "skip_gap_before": True,
    }


def frame_tracks(office, tracks, serializer, base_url):
    if not tracks:
        return tracks
    text = announcement(office)
    try:
        url, path = serializer.get_or_create_clip(text, "speaker", kind="line", raise_on_error=True)
    except Exception as exc:
        raise RuntimeError("Unable to generate the office announcement.") from exc
    if not path:
        raise RuntimeError("Unable to generate the office announcement.")
    intro = {
        "line_id": "audio_office_announcement",
        "module": "Opening",
        "text": text,
        "url": url,
        "path": path,
        "silence_before": 0,
        "silence_after": 0,
        "word_timing": [],
    }
    framed = [intro, bell_track("church_bells", "Opening", "audio_opening_bells", base_url, after=2.5)]
    for position, original in enumerate(tracks):
        track = dict(original)
        if position == 0:
            track["skip_gap_before"] = True
        framed.append(track)
        if track.get("text") == INTERCESSION_INVITATION:
            track["silence_after"] = 0
            framed.extend(
                [
                    bell_track("prayer_chime", INTERCESSION_MODULE, "audio_silence_begin", base_url, after=25),
                    bell_track("prayer_chime", INTERCESSION_MODULE, "audio_silence_end", base_url),
                ]
            )
    framed.append(bell_track("church_bells", "Closing bells", "audio_closing_bells", base_url, before=2))
    return framed
